### ISSUE TITLE
pygn.search(...) returning NoneType object

### ISSUE THREAD

**Issue by NB0174** [cweichen/pygn#14]
Hi, my Gracenote API keys work well (double checked 2 minutes ago). 
When running the file (regardless of IDE), pygn.search(<provided example>) returns a NoneType object.

I have tried running this query on py3.6 and py3.7b, with the same results.

Any ideas as to why ?

**Comment by NB0174** [comment]
Also running test.py provided outputs the following.
```
Search for artist "Kings of Convenience"

null

Search for album "Prism" by "Katy Perry"

null

Search for track "Drop" by "Cornelius"

null

Searching by album TOC

null

Getting artist discography for "Daft Punk"

Traceback (most recent call last):
  File "C:/Users/Gh0sT/Desktop/MP3 Tag Editor/test.py", line 25, in <module>
    result = pygn.get_discography(clientID=clientID, userID=userID, artist='Daft Punk')
  File "C:/Users/Gh0sT/Desktop/MP3 Tag Editor\pygn.py", line 486, in get_discography
    for albumElem in albumElems:
UnboundLocalError: local variable 'albumElems' referenced before assignment
```

**Comment by ehcall** [comment]
I'm having the same problem

**Comment by fredericommartins** [comment]
I have been debugging due to the same NoneType error and it seems like an uncaught exception from Gracenote API in pygn.

In my case I just added a print statemtent after the search query and I got the following response:

> <RESPONSES><MESSAGE>GCSP: Hello error: [130] Please contact Gracenote ODP 17420 [Name: Frederico Martins] [App: Spytify] support.[Gracenote Error 130/74]</MESSAGE><ERROR RETRY="N"> 4003</ERROR> <RESPONSE STATUS="ERROR"></RESPONSE>


It seems to be some clientID difficulty from my app in Gracenote.

**Comment by shillshocked** [comment]
It seems everyone is getting this across the board.

**Comment by AtomicMaya** [comment]
It would seem that their base API has had some changes in how it handles authentification and user sessions (from what little I could gather from debugging a C API in VS that *gasp*, has the same error).
Also some policy changes try to make the service more pro-oriented, so auto-deprecating certain API's by changing the paradigm and not updating the documentation would be an easy way to handle this.

**Comment by shillshocked** [comment]
So what should we do? I've contacted gracenote but to no avail. Do we have to call them?

**Comment by AtomicMaya** [comment]
I am pretty sure that it's all part of their plan to go pro. The best I
could consider is switching API's, probably with a wrapper so as to not
totally have to rebuild from scratch. Especially since the use it has is
audio info, I'm pretty sure there are collaborative projects of a similar
scope that are completely open access, maybe by using a Python API for
MusicBrainz, which seems to work ok, even if not everything is entered in a
timely fashion.

**Comment by tanimislam** [comment]
Concur with @AtomicNicos. I have migrated all my music metadata searching to Musicbrainz using the [musicbrainzngs](https://python-musicbrainzngs.readthedocs.io/en/v0.7.1/) module. Spotify also has a fairly decent API, although not as comprehensive as Musicbrainz's.
